### ISSUE TITLE
救救孩子

### ISSUE THREAD

**Issue by taneui908** [zhaoxilingcheng/163music_comment#1]
F:\Python\Scripts\python.exe F:/sim/下载/163music_comment-main/launch.py
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\sim\AppData\Local\Temp\jieba.cache
Loading model cost 0.797 seconds.
Prefix dict has been built successfully.
7
当前处理的音乐为谭艳-光明（王展鹏 Remix）
爬取评论: 张杰说:《我们都一样》大壮说:《我们不一样》刘斌说:《有啥不一样》许军说:《我不一样》陈慧琳说:《你不一样》蔡依林说:《不一样又怎样》薛之谦说:《你还要我怎样》张赫宣说:《我们不该这样》曹雪说:《怎样才好》刘大毅说:《其实都一样》任贤齐说:《这样也好》叶子妃说:《就这样吧》为了火一次也不容易
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\peewee.py", line 3137, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: comment.comment_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/sim/下载/163music_comment-main/launch.py", line 91, in <module>
    launch()
  File "F:/sim/下载/163music_comment-main/launch.py", line 86, in launch
    comment.save_()
  File "F:\sim\下载\163music_comment-main\models.py", line 40, in save_
    raise e
  File "F:\sim\下载\163music_comment-main\models.py", line 37, in save_
    self.save()
  File "F:\Python\lib\site-packages\peewee.py", line 6549, in save
    pk = self.insert(**field_dict).execute()
  File "F:\Python\lib\site-packages\peewee.py", line 1906, in inner
    return method(self, database, *args, **kwargs)
  File "F:\Python\lib\site-packages\peewee.py", line 1977, in execute
    return self._execute(database)
  File "F:\Python\lib\site-packages\peewee.py", line 2738, in _execute
    return super(Insert, self)._execute(database)
  File "F:\Python\lib\site-packages\peewee.py", line 2473, in _execute
    cursor = database.execute(self)
  File "F:\Python\lib\site-packages\peewee.py", line 3150, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "F:\Python\lib\site-packages\peewee.py", line 3144, in execute_sql
    self.commit()
  File "F:\Python\lib\site-packages\peewee.py", line 2910, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "F:\Python\lib\site-packages\peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "F:\Python\lib\site-packages\peewee.py", line 3137, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: comment.comment_id

Process finished with exit code 1

**Comment by taneui908** [comment]
想爬单个用户的评论，请赐教 ！ 
Thanks♪(･ω･)ﾉ

**Comment by zhaoxilingcheng** [comment]
修复

**Comment by zhaoxilingcheng** [comment]
> 想爬单个用户的评论，请赐教 ！
> Thanks♪(･ω･)ﾉ

那你可以先看看有没有地方可以看到这个用户评论那些音乐列表和内容
才可以爬取的到呢
